apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::176565838937:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1ETBJNMS7D0C1
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      rolearn: arn:aws:iam::176565838937:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-25T21:08:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-25T21:08:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1559"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bcf9d474-299a-4b36-b4c3-d1bb468f1146
